# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Presentacion/UI_Files/UI_Principal.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frm_principal(object):
    def setupUi(self, frm_principal):
        frm_principal.setObjectName("frm_principal")
        frm_principal.resize(1400, 877)
        frm_principal.setStyleSheet("color: rgb(16, 16, 16);\n"
"background-color: rgb(198, 198, 198);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(frm_principal)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frm_db_info = QtWidgets.QFrame(frm_principal)
        self.frm_db_info.setMinimumSize(QtCore.QSize(320, 700))
        self.frm_db_info.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frm_db_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_db_info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_db_info.setObjectName("frm_db_info")
        self.label = QtWidgets.QLabel(self.frm_db_info)
        self.label.setGeometry(QtCore.QRect(10, 270, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lbl_numero_preguntas = QtWidgets.QLabel(self.frm_db_info)
        self.lbl_numero_preguntas.setGeometry(QtCore.QRect(130, 270, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_numero_preguntas.setFont(font)
        self.lbl_numero_preguntas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_numero_preguntas.setObjectName("lbl_numero_preguntas")
        self.label_11 = QtWidgets.QLabel(self.frm_db_info)
        self.label_11.setGeometry(QtCore.QRect(90, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lbl_numero_categorias = QtWidgets.QLabel(self.frm_db_info)
        self.lbl_numero_categorias.setGeometry(QtCore.QRect(140, 310, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_numero_categorias.setFont(font)
        self.lbl_numero_categorias.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_numero_categorias.setObjectName("lbl_numero_categorias")
        self.label_4 = QtWidgets.QLabel(self.frm_db_info)
        self.label_4.setGeometry(QtCore.QRect(10, 310, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frm_db_info)
        self.label_5.setGeometry(QtCore.QRect(190, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frm_db_info)
        self.label_6.setGeometry(QtCore.QRect(10, 350, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.lbl_ruta_bbdd = QtWidgets.QLabel(self.frm_db_info)
        self.lbl_ruta_bbdd.setGeometry(QtCore.QRect(10, 421, 301, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_ruta_bbdd.setFont(font)
        self.lbl_ruta_bbdd.setScaledContents(True)
        self.lbl_ruta_bbdd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_ruta_bbdd.setWordWrap(True)
        self.lbl_ruta_bbdd.setObjectName("lbl_ruta_bbdd")
        self.label_8 = QtWidgets.QLabel(self.frm_db_info)
        self.label_8.setGeometry(QtCore.QRect(10, 400, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.lbl_testtry_icon = QtWidgets.QLabel(self.frm_db_info)
        self.lbl_testtry_icon.setGeometry(QtCore.QRect(10, 10, 301, 101))
        self.lbl_testtry_icon.setStyleSheet("image: url(./Presentacion/resources/LogoBig.png);")
        self.lbl_testtry_icon.setText("")
        self.lbl_testtry_icon.setObjectName("lbl_testtry_icon")
        self.lbl_id_db = QtWidgets.QLabel(self.frm_db_info)
        self.lbl_id_db.setGeometry(QtCore.QRect(40, 230, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_id_db.setFont(font)
        self.lbl_id_db.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_id_db.setObjectName("lbl_id_db")
        self.lbl_db_name = QtWidgets.QLabel(self.frm_db_info)
        self.lbl_db_name.setGeometry(QtCore.QRect(100, 190, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_db_name.setFont(font)
        self.lbl_db_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_db_name.setObjectName("lbl_db_name")
        self.label_9 = QtWidgets.QLabel(self.frm_db_info)
        self.label_9.setGeometry(QtCore.QRect(10, 230, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.frm_db_info)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_15 = QtWidgets.QLabel(self.frm_db_info)
        self.label_15.setGeometry(QtCore.QRect(20, 500, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.frame_4 = QtWidgets.QFrame(self.frm_db_info)
        self.frame_4.setGeometry(QtCore.QRect(10, 509, 301, 211))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btn_guardar_bbdd = QtWidgets.QPushButton(self.frame_4)
        self.btn_guardar_bbdd.setGeometry(QtCore.QRect(20, 120, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_guardar_bbdd.setFont(font)
        self.btn_guardar_bbdd.setObjectName("btn_guardar_bbdd")
        self.btn_cargar_bbdd = QtWidgets.QPushButton(self.frame_4)
        self.btn_cargar_bbdd.setGeometry(QtCore.QRect(20, 20, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cargar_bbdd.setFont(font)
        self.btn_cargar_bbdd.setObjectName("btn_cargar_bbdd")
        self.btn_nueva_bbdd = QtWidgets.QPushButton(self.frame_4)
        self.btn_nueva_bbdd.setGeometry(QtCore.QRect(20, 70, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_nueva_bbdd.setFont(font)
        self.btn_nueva_bbdd.setObjectName("btn_nueva_bbdd")
        self.check_autoload = QtWidgets.QCheckBox(self.frame_4)
        self.check_autoload.setGeometry(QtCore.QRect(10, 180, 281, 22))
        self.check_autoload.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_autoload.setChecked(True)
        self.check_autoload.setTristate(False)
        self.check_autoload.setObjectName("check_autoload")
        self.label.raise_()
        self.lbl_numero_preguntas.raise_()
        self.label_11.raise_()
        self.lbl_numero_categorias.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.lbl_ruta_bbdd.raise_()
        self.label_8.raise_()
        self.lbl_testtry_icon.raise_()
        self.lbl_id_db.raise_()
        self.lbl_db_name.raise_()
        self.label_9.raise_()
        self.label_7.raise_()
        self.frame_4.raise_()
        self.label_15.raise_()
        self.horizontalLayout.addWidget(self.frm_db_info)
        self.frm_tabs = QtWidgets.QTabWidget(frm_principal)
        self.frm_tabs.setEnabled(True)
        self.frm_tabs.setMinimumSize(QtCore.QSize(750, 700))
        self.frm_tabs.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frm_tabs.setObjectName("frm_tabs")
        self.horizontalLayout.addWidget(self.frm_tabs)
        self.frm_options = QtWidgets.QFrame(frm_principal)
        self.frm_options.setMinimumSize(QtCore.QSize(240, 700))
        self.frm_options.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frm_options.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_options.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_options.setObjectName("frm_options")
        self.label_12 = QtWidgets.QLabel(self.frm_options)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.frame_2 = QtWidgets.QFrame(self.frm_options)
        self.frame_2.setGeometry(QtCore.QRect(10, 70, 221, 301))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_analizar_html = QtWidgets.QPushButton(self.frame_2)
        self.btn_analizar_html.setGeometry(QtCore.QRect(10, 120, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_analizar_html.setFont(font)
        self.btn_analizar_html.setObjectName("btn_analizar_html")
        self.btn_delete_db = QtWidgets.QPushButton(self.frame_2)
        self.btn_delete_db.setGeometry(QtCore.QRect(10, 70, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_delete_db.setFont(font)
        self.btn_delete_db.setObjectName("btn_delete_db")
        self.btn_change_bd_name = QtWidgets.QPushButton(self.frame_2)
        self.btn_change_bd_name.setGeometry(QtCore.QRect(10, 20, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_change_bd_name.setFont(font)
        self.btn_change_bd_name.setObjectName("btn_change_bd_name")
        self.btn_print_database_object = QtWidgets.QPushButton(self.frame_2)
        self.btn_print_database_object.setGeometry(QtCore.QRect(10, 170, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_print_database_object.setFont(font)
        self.btn_print_database_object.setObjectName("btn_print_database_object")
        self.btn_clean_database = QtWidgets.QPushButton(self.frame_2)
        self.btn_clean_database.setGeometry(QtCore.QRect(10, 220, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_clean_database.setFont(font)
        self.btn_clean_database.setObjectName("btn_clean_database")
        self.label_13 = QtWidgets.QLabel(self.frm_options)
        self.label_13.setGeometry(QtCore.QRect(20, 61, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.frame_3 = QtWidgets.QFrame(self.frm_options)
        self.frame_3.setGeometry(QtCore.QRect(10, 420, 221, 231))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_rename_categoria = QtWidgets.QPushButton(self.frame_3)
        self.btn_rename_categoria.setGeometry(QtCore.QRect(10, 70, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_rename_categoria.setFont(font)
        self.btn_rename_categoria.setObjectName("btn_rename_categoria")
        self.btn_export_categoria = QtWidgets.QPushButton(self.frame_3)
        self.btn_export_categoria.setGeometry(QtCore.QRect(10, 170, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_export_categoria.setFont(font)
        self.btn_export_categoria.setObjectName("btn_export_categoria")
        self.btn_add_categoria = QtWidgets.QPushButton(self.frame_3)
        self.btn_add_categoria.setGeometry(QtCore.QRect(10, 20, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_add_categoria.setFont(font)
        self.btn_add_categoria.setObjectName("btn_add_categoria")
        self.btn_delete_categoria = QtWidgets.QPushButton(self.frame_3)
        self.btn_delete_categoria.setGeometry(QtCore.QRect(10, 120, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_delete_categoria.setFont(font)
        self.btn_delete_categoria.setObjectName("btn_delete_categoria")
        self.label_14 = QtWidgets.QLabel(self.frm_options)
        self.label_14.setGeometry(QtCore.QRect(30, 410, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.frm_options)

        self.retranslateUi(frm_principal)
        self.frm_tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(frm_principal)

    def retranslateUi(self, frm_principal):
        _translate = QtCore.QCoreApplication.translate
        frm_principal.setWindowTitle(_translate("frm_principal", "Frame"))
        self.label.setText(_translate("frm_principal", "Nº Preguntas:"))
        self.lbl_numero_preguntas.setText(_translate("frm_principal", "null"))
        self.label_11.setText(_translate("frm_principal", "Información"))
        self.lbl_numero_categorias.setText(_translate("frm_principal", "null"))
        self.label_4.setText(_translate("frm_principal", "Nº Categorías:"))
        self.label_5.setText(_translate("frm_principal", "null"))
        self.label_6.setText(_translate("frm_principal", "Última actualización:"))
        self.lbl_ruta_bbdd.setText(_translate("frm_principal", "NINGUNA BBDD CARGADA"))
        self.label_8.setText(_translate("frm_principal", "Ruta:"))
        self.lbl_id_db.setText(_translate("frm_principal", "null"))
        self.lbl_db_name.setText(_translate("frm_principal", "null"))
        self.label_9.setText(_translate("frm_principal", "ID:"))
        self.label_7.setText(_translate("frm_principal", "Nombre:"))
        self.label_15.setText(_translate("frm_principal", "Testtry"))
        self.btn_guardar_bbdd.setText(_translate("frm_principal", "Guardar BBDD "))
        self.btn_cargar_bbdd.setText(_translate("frm_principal", "Cargar BBDD"))
        self.btn_nueva_bbdd.setText(_translate("frm_principal", "Nueva BBDD"))
        self.check_autoload.setText(_translate("frm_principal", "Cargar nueva BBDD automaticamente"))
        self.label_12.setText(_translate("frm_principal", "Opciones"))
        self.btn_analizar_html.setText(_translate("frm_principal", "Analizar html"))
        self.btn_delete_db.setText(_translate("frm_principal", "Eliminar DB"))
        self.btn_change_bd_name.setText(_translate("frm_principal", "Cambiar nombre"))
        self.btn_print_database_object.setText(_translate("frm_principal", "Imprimir objeto"))
        self.btn_clean_database.setText(_translate("frm_principal", "Limpiar preguntas"))
        self.label_13.setText(_translate("frm_principal", "BBDD"))
        self.btn_rename_categoria.setText(_translate("frm_principal", "Renombrar"))
        self.btn_export_categoria.setText(_translate("frm_principal", "Exportar a JSON"))
        self.btn_add_categoria.setText(_translate("frm_principal", "Añadir"))
        self.btn_delete_categoria.setText(_translate("frm_principal", "Eliminar"))
        self.label_14.setText(_translate("frm_principal", "Categoria"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frm_principal = QtWidgets.QFrame()
    ui = Ui_frm_principal()
    ui.setupUi(frm_principal)
    frm_principal.show()
    sys.exit(app.exec_())
