# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Principal.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Utils.Logger as Logger
import Presentacion.CONTROLLER_UI_Principal as Controller

class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()
        self.controller = Controller.Controller()
    
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1388, 824)
        Frame.setStyleSheet("color: rgb(16, 16, 16);\n"
"background-color: rgb(198, 198, 198);")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(10, 10, 381, 411))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 130, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lbl_numero_preguntas = QtWidgets.QLabel(self.frame)
        self.lbl_numero_preguntas.setGeometry(QtCore.QRect(200, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_numero_preguntas.setFont(font)
        self.lbl_numero_preguntas.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_numero_preguntas.setObjectName("lbl_numero_preguntas")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(10, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lbl_numero_categorias = QtWidgets.QLabel(self.frame)
        self.lbl_numero_categorias.setGeometry(QtCore.QRect(200, 160, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_numero_categorias.setFont(font)
        self.lbl_numero_categorias.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_numero_categorias.setObjectName("lbl_numero_categorias")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(200, 190, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.btn_cargar_bbdd = QtWidgets.QPushButton(self.frame)
        self.btn_cargar_bbdd.setGeometry(QtCore.QRect(10, 260, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cargar_bbdd.setFont(font)
        self.btn_cargar_bbdd.setObjectName("btn_cargar_bbdd")
        self.lbl_ruta_bbdd = QtWidgets.QLabel(self.frame)
        self.lbl_ruta_bbdd.setGeometry(QtCore.QRect(10, 350, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_ruta_bbdd.setFont(font)
        self.lbl_ruta_bbdd.setScaledContents(True)
        self.lbl_ruta_bbdd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_ruta_bbdd.setWordWrap(True)
        self.lbl_ruta_bbdd.setObjectName("lbl_ruta_bbdd")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 320, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.btn_nueva_bbdd = QtWidgets.QPushButton(self.frame)
        self.btn_nueva_bbdd.setGeometry(QtCore.QRect(200, 260, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_nueva_bbdd.setFont(font)
        self.btn_nueva_bbdd.setObjectName("btn_nueva_bbdd")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lbl_id_db = QtWidgets.QLabel(self.frame)
        self.lbl_id_db.setGeometry(QtCore.QRect(90, 220, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_id_db.setFont(font)
        self.lbl_id_db.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_id_db.setObjectName("lbl_id_db")
        self.tabWidget = QtWidgets.QTabWidget(Frame)
        self.tabWidget.setGeometry(QtCore.QRect(10, 430, 381, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_opt_bbdd = QtWidgets.QWidget()
        self.tab_opt_bbdd.setObjectName("tab_opt_bbdd")
        self.btn_add_categoria = QtWidgets.QPushButton(self.tab_opt_bbdd)
        self.btn_add_categoria.setGeometry(QtCore.QRect(10, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_add_categoria.setFont(font)
        self.btn_add_categoria.setObjectName("btn_add_categoria")
        self.btn_nueva_bbdd_3 = QtWidgets.QPushButton(self.tab_opt_bbdd)
        self.btn_nueva_bbdd_3.setGeometry(QtCore.QRect(10, 70, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_nueva_bbdd_3.setFont(font)
        self.btn_nueva_bbdd_3.setObjectName("btn_nueva_bbdd_3")
        self.btn_nueva_bbdd_4 = QtWidgets.QPushButton(self.tab_opt_bbdd)
        self.btn_nueva_bbdd_4.setGeometry(QtCore.QRect(10, 130, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_nueva_bbdd_4.setFont(font)
        self.btn_nueva_bbdd_4.setObjectName("btn_nueva_bbdd_4")
        self.tabWidget.addTab(self.tab_opt_bbdd, "")
        self.tab_opt_pregunta = QtWidgets.QWidget()
        self.tab_opt_pregunta.setObjectName("tab_opt_pregunta")
        self.tabWidget.addTab(self.tab_opt_pregunta, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(Frame)
        self.tabWidget_2.setGeometry(QtCore.QRect(400, 10, 981, 791))
        self.tabWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")

        self.retranslateUi(Frame)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Nº Preguntas:"))
        self.lbl_numero_preguntas.setText(_translate("Frame", "null"))
        self.label_11.setText(_translate("Frame", "Información"))
        self.lbl_numero_categorias.setText(_translate("Frame", "null"))
        self.label_4.setText(_translate("Frame", "Nº Categorías:"))
        self.label_5.setText(_translate("Frame", "null"))
        self.label_6.setText(_translate("Frame", "Última actualización:"))
        self.btn_cargar_bbdd.setText(_translate("Frame", "Cargar BBDD Testtry"))
        self.lbl_ruta_bbdd.setText(_translate("Frame", "NINGUNA BBDD CARGADA"))
        self.label_8.setText(_translate("Frame", "Ruta:"))
        self.btn_nueva_bbdd.setText(_translate("Frame", "Nueva BBDD Testtry"))
        self.label_7.setText(_translate("Frame", "ID:"))
        self.lbl_id_db.setText(_translate("Frame", "null"))
        self.btn_add_categoria.setText(_translate("Frame", "Añadir categoría"))
        self.btn_nueva_bbdd_3.setText(_translate("Frame", "Nueva BBDD Testtry"))
        self.btn_nueva_bbdd_4.setText(_translate("Frame", "Nueva BBDD Testtry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_opt_bbdd), _translate("Frame", "Opciones BBDD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_opt_pregunta), _translate("Frame", "Opciones pregunta"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Frame", "Tab 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Frame", "Tab 2"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Frame", "Página"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Frame", "Página"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Frame", "Página"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Frame", "Página"))


# --------------- HASTA AQUI LO QUE HA SIDO GENERADO AUTOMATICAMENTE --------

    def setValues(self):
        pass

    def setActions(self):
        self.btn_cargar_bbdd.clicked.connect(lambda: self.controller.cargarBBDD())
        self.btn_nueva_bbdd.clicked.connect(lambda: self.controller.nuevaBBDD())

        # self.btnSiguiente.clicked.connect(lambda: self.siguientePregunta())
        # self.btnAnterior.clicked.connect(lambda: self.anteriorPregunta())
        # self.btnComprobar.clicked.connect(lambda: self.comprobarRespuesta())
        # self.btnNuevoTest.clicked.connect(lambda: self.nuevoTest())


def start():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    frm_principal = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(frm_principal)
    ui.setValues()
    ui.setActions()
    frm_principal.show()
    sys.exit(app.exec_())
